ALTER TABLE BEA_MNE_COUNTRY ADD ColumnParentCode INT
ALTER TABLE BEA_MNE_COUNTRY ADD ColumnGParentCode INT

ALTER TABLE BEA_MNE_COUNTRY_BY_INDUSTRY ADD ColumnParentCode INT
ALTER TABLE BEA_MNE_COUNTRY_BY_INDUSTRY ADD ColumnGParentCode INT

ALTER TABLE BEA_MNE_COUNTRY_UBO_BY_INDUSTRY ADD ColumnParentCode INT
ALTER TABLE BEA_MNE_COUNTRY_UBO_BY_INDUSTRY ADD ColumnGParentCode INT

ALTER TABLE BEA_MNE_INDUSTRY ADD ColumnParentCode INT
ALTER TABLE BEA_MNE_INDUSTRY ADD ColumnGParentCode INT